
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { FileText, Download, Eye, BarChart3, PieChart, AlertTriangle, Star, Lock } from 'lucide-react';
import { PricingDialog } from './PricingDialog';

interface ValuationReportProps {
  hasPaidAccess?: boolean;
}

export function ValuationReport({ hasPaidAccess = false }: ValuationReportProps) {
  const [showPricingDialog, setShowPricingDialog] = useState(false);

  const handleDownloadClick = () => {
    if (!hasPaidAccess) {
      setShowPricingDialog(true);
    } else {
      // Handle actual download
      console.log('Downloading full report...');
    }
  };

  const handlePlanSelect = (plan: string) => {
    console.log('Selected plan:', plan);
    // Handle plan selection and payment
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-800">Valuation Report</h1>
          <p className="text-slate-600 mt-1">Professional valuation analysis preview</p>
        </div>
        <div className="flex items-center space-x-3">
          <Button onClick={handleDownloadClick} className="bg-valoov-teal hover:bg-valoov-teal/90">
            <Download className="h-4 w-4 mr-2" />
            {hasPaidAccess ? 'Download PDF' : 'Download Full Report'}
          </Button>
        </div>
      </div>

      {/* PDF Preview Section */}
      <Card className="bg-white border-slate-200">
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <FileText className="h-5 w-5 text-valoov-teal" />
            <span className="text-slate-800">Report Preview</span>
            {!hasPaidAccess && (
              <Badge className="bg-valoov-orange/20 text-valoov-orange border-valoov-orange/30">
                Preview Only
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-6">
            {/* Page 1 - Cover Page */}
            <div className="border border-gray-300 rounded-lg overflow-hidden bg-white shadow-sm">
              <div className="p-8 text-center">
                <div className="mb-8">
                  <h1 className="text-3xl font-bold text-slate-800 mb-2">VALUATION REPORT</h1>
                  <div className="w-24 h-1 bg-valoov-teal mx-auto mb-4"></div>
                  <h2 className="text-2xl font-semibold text-slate-700 mb-2">TechCorp Solutions</h2>
                  <p className="text-lg text-slate-600">Benchmarked Business Valuation</p>
                </div>
                
                <div className="bg-slate-50 p-6 rounded-lg mb-8">
                  <div className="grid grid-cols-2 gap-6 text-left">
                    <div>
                      <p className="font-semibold text-slate-800 mb-1">Company:</p>
                      <p className="text-slate-700">TechCorp Solutions Ltd.</p>
                    </div>
                    <div>
                      <p className="font-semibold text-slate-800 mb-1">Industry:</p>
                      <p className="text-slate-700">Financial Technology</p>
                    </div>
                    <div>
                      <p className="font-semibold text-slate-800 mb-1">Valuation Date:</p>
                      <p className="text-slate-700">December 15, 2024</p>
                    </div>
                    <div>
                      <p className="font-semibold text-slate-800 mb-1">Report Type:</p>
                      <p className="text-slate-700">Pre-Money Valuation</p>
                    </div>
                    <div>
                      <p className="font-semibold text-slate-800 mb-1">Stage:</p>
                      <p className="text-slate-700">Series A</p>
                    </div>
                    <div>
                      <p className="font-semibold text-slate-800 mb-1">Revenue (ARR):</p>
                      <p className="text-slate-700">€2.1M</p>
                    </div>
                  </div>
                </div>

                <div className="text-center">
                  <p className="text-sm text-slate-500">Generated by VALOOV</p>
                  <p className="text-sm text-slate-500">Professional Business Valuations</p>
                </div>
              </div>
            </div>

            {/* Page 2 - Executive Summary */}
            <div className="border border-gray-300 rounded-lg overflow-hidden bg-white shadow-sm">
              <div className="p-8">
                <h2 className="text-2xl font-bold text-slate-800 mb-6 border-b border-slate-200 pb-2">Executive Summary</h2>
                
                <div className="mb-8">
                  <div className="bg-gradient-to-r from-valoov-teal/10 to-valoov-orange/10 p-6 rounded-lg text-center mb-6">
                    <h3 className="text-lg font-semibold text-slate-800 mb-2">Company Valuation</h3>
                    <p className="text-4xl font-bold text-valoov-teal mb-1">€3,500,000</p>
                    <p className="text-slate-600">Weighted Average Pre-Money Valuation</p>
                  </div>

                  <div className="grid grid-cols-3 gap-4 mb-6">
                    <div className="text-center p-4 bg-slate-50 rounded-lg">
                      <p className="text-2xl font-bold text-slate-800">€2.9M</p>
                      <p className="text-sm text-slate-600">Minimum Value</p>
                    </div>
                    <div className="text-center p-4 bg-slate-50 rounded-lg">
                      <p className="text-2xl font-bold text-slate-800">€3.5M</p>
                      <p className="text-sm text-slate-600">Most Likely</p>
                    </div>
                    <div className="text-center p-4 bg-slate-50 rounded-lg">
                      <p className="text-2xl font-bold text-slate-800">€4.1M</p>
                      <p className="text-sm text-slate-600">Maximum Value</p>
                    </div>
                  </div>
                </div>

                <div className="text-sm text-slate-700 space-y-4">
                  <p>
                    <strong>Company Overview:</strong> TechCorp Solutions is a Financial Technology company 
                    specializing in B2B SaaS solutions for small and medium enterprises. The company has 
                    shown consistent growth with an Annual Recurring Revenue (ARR) of €2.1M.
                  </p>
                  
                  <p>
                    <strong>Valuation Methodology:</strong> This report employs five industry-standard 
                    valuation methods to provide a comprehensive assessment of the company's fair value.
                  </p>
                </div>
              </div>
            </div>

            {/* Page 3 - Methodology Overview (visible) */}
            <div className="border border-gray-300 rounded-lg overflow-hidden bg-white shadow-sm">
              <div className="p-8">
                <h2 className="text-2xl font-bold text-slate-800 mb-6 border-b border-slate-200 pb-2">Valuation Methodologies</h2>
                
                <div className="space-y-4">
                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-lg">
                    <div>
                      <h4 className="font-semibold text-slate-800">Scorecard Method</h4>
                      <p className="text-sm text-slate-600">Risk-adjusted approach</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xl font-bold text-valoov-teal">€3.2M</p>
                      <p className="text-sm text-slate-600">Weight: 25%</p>
                    </div>
                  </div>

                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-lg">
                    <div>
                      <h4 className="font-semibold text-slate-800">Checklist Method</h4>
                      <p className="text-sm text-slate-600">Qualitative assessment</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xl font-bold text-valoov-teal">€3.8M</p>
                      <p className="text-sm text-slate-600">Weight: 20%</p>
                    </div>
                  </div>

                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-lg">
                    <div>
                      <h4 className="font-semibold text-slate-800">DCF / LTG Method</h4>
                      <p className="text-sm text-slate-600">Long-term growth projections</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xl font-bold text-valoov-teal">€4.1M</p>
                      <p className="text-sm text-slate-600">Weight: 20%</p>
                    </div>
                  </div>

                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-lg">
                    <div>
                      <h4 className="font-semibold text-slate-800">DCF w/ Multiple</h4>
                      <p className="text-sm text-slate-600">Market multiple approach</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xl font-bold text-valoov-teal">€3.5M</p>
                      <p className="text-sm text-slate-600">Weight: 20%</p>
                    </div>
                  </div>

                  <div className="flex justify-between items-center p-4 bg-slate-50 rounded-lg">
                    <div>
                      <h4 className="font-semibold text-slate-800">Venture Capital Method</h4>
                      <p className="text-sm text-slate-600">Exit-based valuation</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xl font-bold text-valoov-teal">€2.9M</p>
                      <p className="text-sm text-slate-600">Weight: 15%</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Blurred/Locked Content */}
            {!hasPaidAccess && (
              <>
                {/* Page 4 - Blurred */}
                <div className="relative border border-gray-300 rounded-lg overflow-hidden">
                  <div className="filter blur-sm bg-white p-8 opacity-60">
                    <h2 className="text-2xl font-bold text-slate-800 mb-6 border-b border-slate-200 pb-2">Detailed Analysis</h2>
                    <div className="space-y-4">
                      <div className="h-6 bg-gray-300 rounded w-full"></div>
                      <div className="h-6 bg-gray-300 rounded w-3/4"></div>
                      <div className="h-6 bg-gray-300 rounded w-1/2"></div>
                      <div className="h-32 bg-gray-200 rounded mt-6"></div>
                      <div className="grid grid-cols-2 gap-4 mt-4">
                        <div className="h-20 bg-gray-200 rounded"></div>
                        <div className="h-20 bg-gray-200 rounded"></div>
                      </div>
                    </div>
                  </div>
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="bg-white p-8 rounded-lg shadow-lg text-center border-2 border-valoov-orange max-w-md">
                      <Lock className="h-12 w-12 mx-auto mb-4 text-valoov-orange" />
                      <h3 className="text-xl font-bold text-slate-800 mb-2">Unlock Full Report</h3>
                      <p className="text-slate-600 mb-4">
                        Get access to 15+ additional pages including:
                      </p>
                      <ul className="text-sm text-slate-600 text-left mb-6 space-y-1">
                        <li>• Detailed methodology calculations</li>
                        <li>• Market analysis & benchmarks</li>
                        <li>• Risk assessment</li>
                        <li>• Financial projections</li>
                        <li>• Investment recommendations</li>
                      </ul>
                      <Button 
                        className="bg-valoov-orange hover:bg-valoov-orange/90 w-full"
                        onClick={handleDownloadClick}
                      >
                        View Pricing Plans
                      </Button>
                    </div>
                  </div>
                </div>

                {/* Additional blurred pages preview */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="border border-gray-300 rounded-lg overflow-hidden filter blur-sm opacity-40">
                    <div className="bg-white p-6">
                      <div className="h-4 bg-gray-300 rounded w-3/4 mb-3"></div>
                      <div className="h-24 bg-gray-200 rounded mb-3"></div>
                      <div className="space-y-2">
                        <div className="h-3 bg-gray-300 rounded w-full"></div>
                        <div className="h-3 bg-gray-300 rounded w-2/3"></div>
                      </div>
                    </div>
                  </div>
                  <div className="border border-gray-300 rounded-lg overflow-hidden filter blur-sm opacity-40">
                    <div className="bg-white p-6">
                      <div className="h-4 bg-gray-300 rounded w-3/4 mb-3"></div>
                      <div className="h-24 bg-gray-200 rounded mb-3"></div>
                      <div className="space-y-2">
                        <div className="h-3 bg-gray-300 rounded w-full"></div>
                        <div className="h-3 bg-gray-300 rounded w-2/3"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </>
            )}

            {hasPaidAccess && (
              <div className="text-center p-8 bg-green-50 rounded-lg">
                <div className="flex items-center justify-center space-x-2 mb-4">
                  <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                  <p className="font-semibold text-green-800">Full Report Access Granted</p>
                </div>
                <p className="text-green-700">
                  You have access to the complete 20+ page valuation report.
                </p>
              </div>
            )}

            {!hasPaidAccess && (
              <div className="text-center p-6 bg-slate-50 rounded-lg border-2 border-dashed border-slate-300">
                <p className="text-slate-600 mb-4">
                  <strong>Preview includes 3 of 20+ pages.</strong> Purchase a plan to download the complete professional report.
                </p>
                <Button 
                  onClick={handleDownloadClick}
                  className="bg-valoov-teal hover:bg-valoov-teal/90"
                >
                  Get Full Report Access
                </Button>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Pricing Dialog */}
      <PricingDialog
        isOpen={showPricingDialog}
        onClose={() => setShowPricingDialog(false)}
        onPlanSelect={handlePlanSelect}
      />
    </div>
  );
}
